### ISSUE TITLE
What server i need to use?

### ISSUE THREAD

**Issue by yemake** [CA1R7/yurex-client#2]
Is it possible to share your server and backend? =)

Cant find the correct server for it

**Comment by yemake** [comment]
We use it to play with friends, but I couldn't get everything to work properly because I might not be using the correct version or you made some custom modifications. The online player count isn't showing, and when I open the mini-map, it doesn't work on mobile. I'm not quite sure what the issue is. I would really appreciate it if you could share some information.

**Comment by CA1R7** [comment]
@yemake what for, i can give you access to the backend and server too as well, contact me on discord cairbyte71
